name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - master
      - main

jobs:
  build-image-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Backend Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Backend Docker Image
      run: |
        docker build -t narwal25/wwa-backend:${{ github.sha }} .
        docker push narwal25/wwa-backend:${{ github.sha }}

    - name: Output image tag
      run: echo "IMAGE_TAG=narwal25/wwa-backend:${{ github.sha }}" >> $GITHUB_ENV
